# This example provides a basic configuration and description based on the M5STACK components
# For further configuration you should visit the ESPHome docs https://esphome.io
# Every line starting with a # can be removed.

## BASIC CONFIGURATION
esphome:
  name: samsung_ac
  friendly_name: Climate

# Select chipset and board configuration - in this case M5STACK
esp32:
  board: m5stack-atom

# [Optional] - Create web interface where you can control the AC from your web browser (without Home Assistant)
web_server:
  port: 80

# Enable logging
logger:
  logs:
    component: ERROR # Remove the "Your component takes to long to respond warning"

# Enable native API for communication with Home Assistant, this can be removed if you do not plan to use it with Home Assistant
api:

# Enable OTA firmware update, you will be able to upload the firmware over WiFi without connecting the device by cables
ota:
  platform: esphome

# Setup your WiFi password
wifi:
  ssid: "Mosh Potats" # !!!CHANGE ME!!!
  password: "hippopotats123" # !!!CHANGE ME!!!

captive_portal:

# Specify pins used by the board to comunicate with RS485 board - in this case M5STACK
uart:
  tx_pin: GPIO19   # Use GPIO26 for ATOM Tail485 
  rx_pin: GPIO22   # Use GPIO32 for ATOM Tail485
  # For older devices it could also be 2400. But you should start with 9600.
  baud_rate: 9600
  parity: EVEN

## SAMSUNG AC CONFIGURATION

# Import custom component from GitHub
external_components:
  #- source: github://atanasenko/esphome_samsung_hvac_bus@transport # Use @stable if you want a more stable experience, but note a lot of this example code breaks.
  - source: github://brazoayeye/esphome_samsung_ac@main
    components: [samsung_ac]

# Configuration of AC component
samsung_ac:

  # For NonNASA devices the following option can be enabled to prevent the device from sleeping when idle. This allows
  # values like internal and external temperature to continue to be tracked when the device isn't in use.
  
  # When enabled (set to true), this option will log the messages associated with undefined codes on the device. This is useful for debugging and identifying any unexpected or unknown codes that the device may receive during operation.
  
  # When enabled (set to true), this option logs messages associated with defined codes on the device. This helps in monitoring the behavior of the device by recording the activity related to known, expected codes.
  debug_log_messages: false

  # For half duplex RS485 board with DI, DE, RE, and RO pins, you have to control read/write with control pin
  # see https://microcontrollerslab.com/rs485-serial-communication-esp32-esp8266-tutorial/ for wiring
  #flow_control_pin: GPIO4

  devices:
    # Skip everything below on the first run! Wait a minute, watch your ESPHome logs until you see the "Discovered devices:" section and you see some addresses:
    # For NASA devices it looks like this (with 1 outdoor device and 4 indoor devices): 
    #   Outdoor: 10.00.00
    #   Indoor:  20.00.00, 20.00.01, 20.00.02, 20.00.03
    # For NonNASA devices it looks like this (with 2 indoor devices): 
    #   Indoor:  00, 01
    # You need these addresses for the the sections below. If you see only a "-" then you should visit the troubleshooting section in the readme. 

    # Repeat everything below for each indoor device address you see in your logs
    - address: "20.00.00" # Indoor device address 
      # Each property below is optional (climate, room_temperature etc.) - you can delete those which you dont need.
      # For the names we suggest to choose a combination of room name and the thing it controls. 

      # Configures/overrides the capabilites for this devices. 
      # Look above for all options.
      custom_climate:
        - name: "Water heater"
          status_addr: 0x4237 # mandatory address regarding status temperature
          set_addr: 0x4235    # mandatory address regarding setpoint temperature
          set_min: 40         # optional, default = 25°C
          set_max: 65         # optional, default = 65°C
          enable_addr: 0x4065 # mandatory enabling address, only 1/0 should be written there. Look at mode sub section
                              # By default the value is set = 1 when HA send a value > 0.
          preset:         
            addr: 0x4066      # Address for presets
            ClimatePreset0Value: 1 # CLIMATE_PRESET_NONE => 1 Standard
            ClimatePreset1Value: -1 # CLIMATE_PRESET_HOME 
            ClimatePreset2Value: -1 # CLIMATE_PRESET_AWAY 
            ClimatePreset3Value: 2 # CLIMATE_PRESET_BOOST => 2 Power
            ClimatePreset4Value: -1 # CLIMATE_PRESET_COMFORT 
            ClimatePreset5Value: 0 # CLIMATE_PRESET_ECO => 0 Eco
            ClimatePreset6Value: -1 # CLIMATE_PRESET_SLEEP 
            ClimatePreset7Value: 3 # CLIMATE_PRESET_ACTIVITY  => 3 Force
          visual:
            temperature_step:
              target_temperature: 1
              current_temperature: 0.1

            
        - name: "Heating"
          status_addr: 0x4238
          set_addr: 0x4247
          set_min: 30          # large enough to let both ranges for heating (25-65)°C and cooling (8-25)°C
          set_max: 65
          enable_addr: 0x4000
          mode:
            addr: 0x4001      # In this case the single ClimateMode is splitted between the enable_addr and the mode->addr
                              # https://esphome.io/api/namespaceesphome_1_1climate#a8716cd7ed01ceb7ccedfa2f7b47a39d2
                              # As before, the enable_addr is set = 1 for each mode > 0. If a value of enable is read = 0 from nasa,
                              # a value of CLIMATE_MODE_OFF is sent to HA regardless of the value of the register mode->addr
            #ClimateMode0Value:  # Default -1 = CLIMATE_MODE_OFF is not translated into mode->addr
            #ClimateMode1Value:  # Default -1 = CLIMATE_MODE_HEAT_COOL is not translated into mode->addr     
            ClimateMode2Value: 1 # Default -1. Setting =1 the value CLIMATE_MODE_COOL==2 is translated as 1 into mode->addr
            ClimateMode3Value: 4 # Default -1. Setting = 4 the value CLIMATE_MODE_HEAT==3 is translated as 4 into mode->addr
            #ClimateMode4Value: -1
            #ClimateMode5Value: -1
            ClimateMode6Value: 0 # Default -1. Setting = 4 the value CLIMATE_MODE_AUTO==6 is translated as 0 into mode->add
          visual:
            temperature_step:
              target_temperature: 0.1
              current_temperature: 0.1
              
      custom_sensor:
        - name: Produced energy
          message: 0x4427
          device_class: energy
          state_class: total_increasing
          unit_of_measurement: kWh

    - address: "10.00.00" # external unit
      custom_sensor:
        - name: External temperature
          message: 0x8204
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: Flow Rate
          message: 0x823D
          state_class: measurement
          unit_of_measurement: L/min
          accuracy_decimals: 3

        - name: Power consumption
          message: 0x8413
          device_class: power
          state_class: measurement
          unit_of_measurement: W
        - name: Consumed energy
          message: 0x8414
          device_class: energy
          state_class: total_increasing
          unit_of_measurement: kWh
          accuracy_decimals: 1
          filters:
            - multiply: 0.001
        - name: Heat pump voltage
          message: 0x24fc
          device_class: voltage
          state_class: measurement
          unit_of_measurement: V
        - name: Compressor Frequency
          message: 0x8238
          device_class: frequency
          state_class: measurement
          unit_of_measurement: Hz
          accuracy_decimals: 1
        - name: Target Compressor Frequency
          message: 0x8237
          device_class: frequency
          state_class: measurement
          unit_of_measurement: Hz
          accuracy_decimals: 1
        - name: Fan Speed
          message: 0x823D
          state_class: measurement
          unit_of_measurement: RPM
          accuracy_decimals: 1


        - name: VAR_IN_TEMP_TARGET_F_4201
          message: 0x4201
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_4202
          message: 0x4202
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_ROOM_F_4203
          message: 0x4203
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_4204
          message: 0x4204
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_EVA_IN_F_4205
          message: 0x4205
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_EVA_OUT_F_4206
          message: 0x4206
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_420C
          message: 0x420C
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_WATER_HEATER_TARGET_F_4235
          message: 0x4235
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_WATER_IN_F_4236
          message: 0x4236
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_WATER_TANK_F_4237
          message: 0x4237
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_WATER_OUT_F_4238
          message: 0x4238
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_WATER_OUT2_F_4239
          message: 0x4239
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_WATER_OUTLET_TARGET_F_4247
          message: 0x4247
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_WATER_LAW_TARGET_F_4248
          message: 0x4248
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_WATER_LAW_F_427F
          message: 0x427F
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_MIXING_VALVE_F_428C
          message: 0x428C
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_ZONE2_F_42D4
          message: 0x42D4
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_TARGET_ZONE2_F_42D6
          message: 0x42D6
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_WATER_OUTLET_TARGET_ZONE2_F_42D7
          message: 0x42D7
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_WATER_OUTLET_ZONE1_F_42D8
          message: 0x42D8
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1

        - name: VAR_IN_TEMP_WATER_OUTLET_ZONE2_F_42D9
          message: 0x42D9
          device_class: temperature
          state_class: measurement
          unit_of_measurement: "°C"
          filters:
            - multiply: 0.1
          accuracy_decimals: 1


          # :bottom
          #TEMP 1 : Mid
          #Mixing Valve Temp: Top
          #VAR_IN_FLOW_SENSOR_CALC_42E9 = 0x42E9,
          #VAR_IN_TEMP_WATER_IN_F_4236 = 0x4236
          #VAR_IN_TEMP_WATER_OUT_F_4238 = 0x4238,

